### ISSUE TITLE
Thank you for installing Weekly Digest

### ISSUE THREAD

**Issue by abhijeetps** [thefrontside/emberx-xml-http-request#15]
Hi, maintainers at [thefrontside](https://github.com/thefrontside)!
Thank you for installing this app as a test in your repository. 😄 
I will be watching this repository to see app performance while it is installed.
Out of curiosity, can you please answer whether the **weekly-digest** label was 'grey' colored at the time of installing, or have you modified it. 
Thanks. 😄

**Comment by abhijeetps** [comment]
That's weird, it didn't created a `.github/weekly-digest.yml` file in the repository also. 😕

**Comment by cowboyd** [comment]
duplicate of #14
